version: '3.8'

services:
  api-gateway:
    container_name: api_gateway
    build: ./
    ports:
      - "8081:8081"
    networks:
      - global-network

  postgres:
      image: postgres:14
      container_name: postgres_dock
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: booking
      ports:
        - "5432:5432"
      networks:
        - global-network
# Docker Networks
networks:
  global-network:
    external: true 
