// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: protos/access.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessPersonal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingPersonalId string `protobuf:"bytes,1,opt,name=booking_personal_id,json=bookingPersonalId,proto3" json:"booking_personal_id,omitempty"`
	Date              string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *AccessPersonal) Reset() {
	*x = AccessPersonal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessPersonal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPersonal) ProtoMessage() {}

func (x *AccessPersonal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPersonal.ProtoReflect.Descriptor instead.
func (*AccessPersonal) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessPersonal) GetBookingPersonalId() string {
	if x != nil {
		return x.BookingPersonalId
	}
	return ""
}

func (x *AccessPersonal) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateAccessPersonalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessPersonal *AccessPersonal `protobuf:"bytes,1,opt,name=access_personal,json=accessPersonal,proto3" json:"access_personal,omitempty"`
}

func (x *CreateAccessPersonalRequest) Reset() {
	*x = CreateAccessPersonalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessPersonalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessPersonalRequest) ProtoMessage() {}

func (x *CreateAccessPersonalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessPersonalRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessPersonalRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccessPersonalRequest) GetAccessPersonal() *AccessPersonal {
	if x != nil {
		return x.AccessPersonal
	}
	return nil
}

type ListAccessPersonalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingPersonalId string `protobuf:"bytes,1,opt,name=booking_personal_id,json=bookingPersonalId,proto3" json:"booking_personal_id,omitempty"`
}

func (x *ListAccessPersonalRequest) Reset() {
	*x = ListAccessPersonalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessPersonalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessPersonalRequest) ProtoMessage() {}

func (x *ListAccessPersonalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessPersonalRequest.ProtoReflect.Descriptor instead.
func (*ListAccessPersonalRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{2}
}

func (x *ListAccessPersonalRequest) GetBookingPersonalId() string {
	if x != nil {
		return x.BookingPersonalId
	}
	return ""
}

type ListAccessPersonalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessPersonal []*AccessPersonal `protobuf:"bytes,1,rep,name=access_personal,json=accessPersonal,proto3" json:"access_personal,omitempty"`
}

func (x *ListAccessPersonalResponse) Reset() {
	*x = ListAccessPersonalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessPersonalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessPersonalResponse) ProtoMessage() {}

func (x *ListAccessPersonalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessPersonalResponse.ProtoReflect.Descriptor instead.
func (*ListAccessPersonalResponse) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccessPersonalResponse) GetAccessPersonal() []*AccessPersonal {
	if x != nil {
		return x.AccessPersonal
	}
	return nil
}

type AccessGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingGroupId string `protobuf:"bytes,1,opt,name=booking_group_id,json=bookingGroupId,proto3" json:"booking_group_id,omitempty"`
	Date           string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *AccessGroup) Reset() {
	*x = AccessGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessGroup) ProtoMessage() {}

func (x *AccessGroup) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessGroup.ProtoReflect.Descriptor instead.
func (*AccessGroup) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{4}
}

func (x *AccessGroup) GetBookingGroupId() string {
	if x != nil {
		return x.BookingGroupId
	}
	return ""
}

func (x *AccessGroup) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateAccessGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessGroup *AccessGroup `protobuf:"bytes,1,opt,name=access_group,json=accessGroup,proto3" json:"access_group,omitempty"`
}

func (x *CreateAccessGroupRequest) Reset() {
	*x = CreateAccessGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessGroupRequest) ProtoMessage() {}

func (x *CreateAccessGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessGroupRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccessGroupRequest) GetAccessGroup() *AccessGroup {
	if x != nil {
		return x.AccessGroup
	}
	return nil
}

type ListAccessGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingGroupId string `protobuf:"bytes,1,opt,name=booking_group_id,json=bookingGroupId,proto3" json:"booking_group_id,omitempty"`
}

func (x *ListAccessGroupRequest) Reset() {
	*x = ListAccessGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessGroupRequest) ProtoMessage() {}

func (x *ListAccessGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessGroupRequest.ProtoReflect.Descriptor instead.
func (*ListAccessGroupRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccessGroupRequest) GetBookingGroupId() string {
	if x != nil {
		return x.BookingGroupId
	}
	return ""
}

type ListAccessGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessGroup []*AccessGroup `protobuf:"bytes,1,rep,name=access_group,json=accessGroup,proto3" json:"access_group,omitempty"`
}

func (x *ListAccessGroupResponse) Reset() {
	*x = ListAccessGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessGroupResponse) ProtoMessage() {}

func (x *ListAccessGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessGroupResponse.ProtoReflect.Descriptor instead.
func (*ListAccessGroupResponse) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccessGroupResponse) GetAccessGroup() []*AccessGroup {
	if x != nil {
		return x.AccessGroup
	}
	return nil
}

type AccessCoach struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingCoachId string `protobuf:"bytes,1,opt,name=booking_coach_id,json=bookingCoachId,proto3" json:"booking_coach_id,omitempty"`
	Date           string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *AccessCoach) Reset() {
	*x = AccessCoach{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCoach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCoach) ProtoMessage() {}

func (x *AccessCoach) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCoach.ProtoReflect.Descriptor instead.
func (*AccessCoach) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{8}
}

func (x *AccessCoach) GetBookingCoachId() string {
	if x != nil {
		return x.BookingCoachId
	}
	return ""
}

func (x *AccessCoach) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateAccessCoachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessCoach *AccessCoach `protobuf:"bytes,1,opt,name=access_coach,json=accessCoach,proto3" json:"access_coach,omitempty"`
}

func (x *CreateAccessCoachRequest) Reset() {
	*x = CreateAccessCoachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessCoachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessCoachRequest) ProtoMessage() {}

func (x *CreateAccessCoachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessCoachRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessCoachRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAccessCoachRequest) GetAccessCoach() *AccessCoach {
	if x != nil {
		return x.AccessCoach
	}
	return nil
}

type ListAccessCoachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingCoachId string `protobuf:"bytes,1,opt,name=booking_coach_id,json=bookingCoachId,proto3" json:"booking_coach_id,omitempty"`
}

func (x *ListAccessCoachRequest) Reset() {
	*x = ListAccessCoachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessCoachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessCoachRequest) ProtoMessage() {}

func (x *ListAccessCoachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessCoachRequest.ProtoReflect.Descriptor instead.
func (*ListAccessCoachRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccessCoachRequest) GetBookingCoachId() string {
	if x != nil {
		return x.BookingCoachId
	}
	return ""
}

type ListAccessCoachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessCoach []*AccessCoach `protobuf:"bytes,1,rep,name=access_coach,json=accessCoach,proto3" json:"access_coach,omitempty"`
}

func (x *ListAccessCoachResponse) Reset() {
	*x = ListAccessCoachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAccessCoachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessCoachResponse) ProtoMessage() {}

func (x *ListAccessCoachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessCoachResponse.ProtoReflect.Descriptor instead.
func (*ListAccessCoachResponse) Descriptor() ([]byte, []int) {
	return file_protos_access_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccessCoachResponse) GetAccessCoach() []*AccessCoach {
	if x != nil {
		return x.AccessCoach
	}
	return nil
}

var File_protos_access_proto protoreflect.FileDescriptor

var file_protos_access_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x79, 0x6d, 0x22, 0x54, 0x0a, 0x0e, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x5b, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3c, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x0e, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0x4b, 0x0a,
	0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x1a, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0x4b, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x22, 0x42, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x79, 0x6d, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x4b, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x61, 0x63,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x22, 0x42, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x61, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x17, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x63, 0x6f, 0x61, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x79,
	0x6d, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x32, 0xdd, 0x03, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x55, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x12, 0x1e, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x4c, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b, 0x2e, 0x67, 0x79,
	0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x67, 0x79,
	0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f,
	0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x79, 0x6d,
	0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x12, 0x4c, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x12,
	0x1b, 0x2e, 0x67, 0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67,
	0x79, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x61,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_access_proto_rawDescOnce sync.Once
	file_protos_access_proto_rawDescData = file_protos_access_proto_rawDesc
)

func file_protos_access_proto_rawDescGZIP() []byte {
	file_protos_access_proto_rawDescOnce.Do(func() {
		file_protos_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_access_proto_rawDescData)
	})
	return file_protos_access_proto_rawDescData
}

var file_protos_access_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_access_proto_goTypes = []any{
	(*AccessPersonal)(nil),              // 0: gym.AccessPersonal
	(*CreateAccessPersonalRequest)(nil), // 1: gym.CreateAccessPersonalRequest
	(*ListAccessPersonalRequest)(nil),   // 2: gym.ListAccessPersonalRequest
	(*ListAccessPersonalResponse)(nil),  // 3: gym.ListAccessPersonalResponse
	(*AccessGroup)(nil),                 // 4: gym.AccessGroup
	(*CreateAccessGroupRequest)(nil),    // 5: gym.CreateAccessGroupRequest
	(*ListAccessGroupRequest)(nil),      // 6: gym.ListAccessGroupRequest
	(*ListAccessGroupResponse)(nil),     // 7: gym.ListAccessGroupResponse
	(*AccessCoach)(nil),                 // 8: gym.AccessCoach
	(*CreateAccessCoachRequest)(nil),    // 9: gym.CreateAccessCoachRequest
	(*ListAccessCoachRequest)(nil),      // 10: gym.ListAccessCoachRequest
	(*ListAccessCoachResponse)(nil),     // 11: gym.ListAccessCoachResponse
}
var file_protos_access_proto_depIdxs = []int32{
	0,  // 0: gym.CreateAccessPersonalRequest.access_personal:type_name -> gym.AccessPersonal
	0,  // 1: gym.ListAccessPersonalResponse.access_personal:type_name -> gym.AccessPersonal
	4,  // 2: gym.CreateAccessGroupRequest.access_group:type_name -> gym.AccessGroup
	4,  // 3: gym.ListAccessGroupResponse.access_group:type_name -> gym.AccessGroup
	8,  // 4: gym.CreateAccessCoachRequest.access_coach:type_name -> gym.AccessCoach
	8,  // 5: gym.ListAccessCoachResponse.access_coach:type_name -> gym.AccessCoach
	1,  // 6: gym.AccessService.CreateAccessPersonal:input_type -> gym.CreateAccessPersonalRequest
	2,  // 7: gym.AccessService.ListAccessPersonal:input_type -> gym.ListAccessPersonalRequest
	5,  // 8: gym.AccessService.CreateAccessGroup:input_type -> gym.CreateAccessGroupRequest
	6,  // 9: gym.AccessService.ListAccessGroup:input_type -> gym.ListAccessGroupRequest
	9,  // 10: gym.AccessService.CreateAccessCoach:input_type -> gym.CreateAccessCoachRequest
	10, // 11: gym.AccessService.ListAccessCoach:input_type -> gym.ListAccessCoachRequest
	0,  // 12: gym.AccessService.CreateAccessPersonal:output_type -> gym.AccessPersonal
	3,  // 13: gym.AccessService.ListAccessPersonal:output_type -> gym.ListAccessPersonalResponse
	4,  // 14: gym.AccessService.CreateAccessGroup:output_type -> gym.AccessGroup
	7,  // 15: gym.AccessService.ListAccessGroup:output_type -> gym.ListAccessGroupResponse
	8,  // 16: gym.AccessService.CreateAccessCoach:output_type -> gym.AccessCoach
	11, // 17: gym.AccessService.ListAccessCoach:output_type -> gym.ListAccessCoachResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protos_access_proto_init() }
func file_protos_access_proto_init() {
	if File_protos_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_access_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccessPersonal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAccessPersonalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessPersonalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessPersonalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AccessGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAccessGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AccessCoach); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAccessCoachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessCoachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListAccessCoachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_access_proto_goTypes,
		DependencyIndexes: file_protos_access_proto_depIdxs,
		MessageInfos:      file_protos_access_proto_msgTypes,
	}.Build()
	File_protos_access_proto = out.File
	file_protos_access_proto_rawDesc = nil
	file_protos_access_proto_goTypes = nil
	file_protos_access_proto_depIdxs = nil
}
