// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: protos/access_beta.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessBetaPersonalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SportHallId string `protobuf:"bytes,2,opt,name=sport_hall_id,json=sportHallId,proto3" json:"sport_hall_id,omitempty"`
}

func (x *AccessBetaPersonalRequest) Reset() {
	*x = AccessBetaPersonalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_beta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessBetaPersonalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessBetaPersonalRequest) ProtoMessage() {}

func (x *AccessBetaPersonalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_beta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessBetaPersonalRequest.ProtoReflect.Descriptor instead.
func (*AccessBetaPersonalRequest) Descriptor() ([]byte, []int) {
	return file_protos_access_beta_proto_rawDescGZIP(), []int{0}
}

func (x *AccessBetaPersonalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessBetaPersonalRequest) GetSportHallId() string {
	if x != nil {
		return x.SportHallId
	}
	return ""
}

type AccessBetaPersonalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "granted" or "denied"
}

func (x *AccessBetaPersonalResponse) Reset() {
	*x = AccessBetaPersonalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_access_beta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessBetaPersonalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessBetaPersonalResponse) ProtoMessage() {}

func (x *AccessBetaPersonalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_access_beta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessBetaPersonalResponse.ProtoReflect.Descriptor instead.
func (*AccessBetaPersonalResponse) Descriptor() ([]byte, []int) {
	return file_protos_access_beta_proto_rawDescGZIP(), []int{1}
}

func (x *AccessBetaPersonalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_access_beta_proto protoreflect.FileDescriptor

var file_protos_access_beta_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x62, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x79, 0x6d, 0x22,
	0x58, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x65, 0x74, 0x61, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x68,
	0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1a, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x65, 0x74, 0x61, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x67, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x65, 0x74, 0x61, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x79, 0x6d, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x65, 0x74, 0x61, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x79, 0x6d, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x65, 0x74, 0x61, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_access_beta_proto_rawDescOnce sync.Once
	file_protos_access_beta_proto_rawDescData = file_protos_access_beta_proto_rawDesc
)

func file_protos_access_beta_proto_rawDescGZIP() []byte {
	file_protos_access_beta_proto_rawDescOnce.Do(func() {
		file_protos_access_beta_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_access_beta_proto_rawDescData)
	})
	return file_protos_access_beta_proto_rawDescData
}

var file_protos_access_beta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_access_beta_proto_goTypes = []any{
	(*AccessBetaPersonalRequest)(nil),  // 0: gym.AccessBetaPersonalRequest
	(*AccessBetaPersonalResponse)(nil), // 1: gym.AccessBetaPersonalResponse
}
var file_protos_access_beta_proto_depIdxs = []int32{
	0, // 0: gym.AccessServiceBeta.CheckUserAccess:input_type -> gym.AccessBetaPersonalRequest
	1, // 1: gym.AccessServiceBeta.CheckUserAccess:output_type -> gym.AccessBetaPersonalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_access_beta_proto_init() }
func file_protos_access_beta_proto_init() {
	if File_protos_access_beta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_access_beta_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccessBetaPersonalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_access_beta_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccessBetaPersonalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_access_beta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_access_beta_proto_goTypes,
		DependencyIndexes: file_protos_access_beta_proto_depIdxs,
		MessageInfos:      file_protos_access_beta_proto_msgTypes,
	}.Build()
	File_protos_access_beta_proto = out.File
	file_protos_access_beta_proto_rawDesc = nil
	file_protos_access_beta_proto_goTypes = nil
	file_protos_access_beta_proto_depIdxs = nil
}
