// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: protos/access_beta.proto

package booking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessServiceBeta_CheckUserAccess_FullMethodName = "/gym.AccessServiceBeta/CheckUserAccess"
)

// AccessServiceBetaClient is the client API for AccessServiceBeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessServiceBetaClient interface {
	CheckUserAccess(ctx context.Context, in *AccessBetaPersonalRequest, opts ...grpc.CallOption) (*AccessBetaPersonalResponse, error)
}

type accessServiceBetaClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceBetaClient(cc grpc.ClientConnInterface) AccessServiceBetaClient {
	return &accessServiceBetaClient{cc}
}

func (c *accessServiceBetaClient) CheckUserAccess(ctx context.Context, in *AccessBetaPersonalRequest, opts ...grpc.CallOption) (*AccessBetaPersonalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessBetaPersonalResponse)
	err := c.cc.Invoke(ctx, AccessServiceBeta_CheckUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceBetaServer is the server API for AccessServiceBeta service.
// All implementations must embed UnimplementedAccessServiceBetaServer
// for forward compatibility.
type AccessServiceBetaServer interface {
	CheckUserAccess(context.Context, *AccessBetaPersonalRequest) (*AccessBetaPersonalResponse, error)
	mustEmbedUnimplementedAccessServiceBetaServer()
}

// UnimplementedAccessServiceBetaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceBetaServer struct{}

func (UnimplementedAccessServiceBetaServer) CheckUserAccess(context.Context, *AccessBetaPersonalRequest) (*AccessBetaPersonalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserAccess not implemented")
}
func (UnimplementedAccessServiceBetaServer) mustEmbedUnimplementedAccessServiceBetaServer() {}
func (UnimplementedAccessServiceBetaServer) testEmbeddedByValue()                           {}

// UnsafeAccessServiceBetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceBetaServer will
// result in compilation errors.
type UnsafeAccessServiceBetaServer interface {
	mustEmbedUnimplementedAccessServiceBetaServer()
}

func RegisterAccessServiceBetaServer(s grpc.ServiceRegistrar, srv AccessServiceBetaServer) {
	// If the following call pancis, it indicates UnimplementedAccessServiceBetaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessServiceBeta_ServiceDesc, srv)
}

func _AccessServiceBeta_CheckUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessBetaPersonalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceBetaServer).CheckUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessServiceBeta_CheckUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceBetaServer).CheckUserAccess(ctx, req.(*AccessBetaPersonalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessServiceBeta_ServiceDesc is the grpc.ServiceDesc for AccessServiceBeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessServiceBeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gym.AccessServiceBeta",
	HandlerType: (*AccessServiceBetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUserAccess",
			Handler:    _AccessServiceBeta_CheckUserAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/access_beta.proto",
}
